import { ApiProperty } from '@nestjs/swagger';

export class OracleSubmitRewardsDto {
  @ApiProperty({
    name: 'activatedValidators',
    description: 'The total number of activated validators (removed validators are not deducted)',
    example: 34,
    required: true,
  })
  readonly activatedValidators: number;

  @ApiProperty({
    name: 'exitedValidators',
    description: 'The total number of (voluntary) exited validators',
    example: 34,
    required: true,
  })
  readonly exitedValidators: number;

  @ApiProperty({
    name: 'totalRewards',
    description:
      'Total amount of rewards (withdrawals) in wei, generated by all the pool validators',
    example: '100000000000',
    required: true,
  })
  readonly totalRewards: string;

  @ApiProperty({
    name: 'signature',
    description: 'Signature of the oracle',
    example: '0x1234567890...',
    required: true,
  })
  readonly signature: string;
}
