import { ApiProperty } from '@nestjs/swagger';

export class RewardsContractStateDto {
  @ApiProperty({
    name: 'contractBalance',
    description: 'The balance of the contract, in wei',
    example: '1000000000000000000',
    required: true,
  })
  readonly contractBalance: string;

  @ApiProperty({
    name: 'feeRecipientRewardsBalance',
    description: 'The amount of rewards available for the fee recipient, in wei',
    example: '10000000000000',
    required: true,
  })
  readonly feeRecipientRewardsBalance: string;

  @ApiProperty({
    name: 'protocolFeeRecipient',
    description: 'The address of the protocol fee recipient',
    example: '0x123...',
    required: true,
  })
  readonly protocolFeeRecipient: string;

  @ApiProperty({
    name: 'protocolFee',
    description: 'The fee taken by the protocol, in percentage',
    example: 10, // 10%
    required: true,
  })
  readonly protocolFee: number;

  @ApiProperty({
    name: 'totalRewards',
    description: 'The total rewards amount generated by the protocol, in wei',
    example: '100000000000000000',
    required: true,
  })
  readonly totalRewards: string;

  @ApiProperty({
    name: 'totalFeesCollected',
    description: 'The amount of fees collected through the execution layer, in wei',
    example: '100000000000000000',
    required: true,
  })
  readonly totalFeesCollected: string;

  @ApiProperty({
    name: 'totalCashedOut',
    description: 'The amount of rewards cashed out, in wei',
    example: '100000000000000000',
    required: true,
  })
  readonly totalCashedOut: string;

  @ApiProperty({
    name: 'rewardPerToken',
    description: 'The reward per token (for reward calculation), in wei',
    example: '100000000000000000',
    required: true,
  })
  readonly rewardPerToken: string;

  @ApiProperty({
    name: 'totalAvailableRewards',
    description: 'The total amount of rewards claimable, in wei',
    example: '100000000000000000',
    required: true,
  })
  readonly totalAvailableRewards: string;
}
