export enum VALIDATOR_STATUS {
  PENDING_INITIALIZED = 'pending_initialized',
  PENDING = 'pending',
  PENDING_QUEUED = 'pending_queued',
  ACTIVE_ONGOING = 'active_ongoing',
  ACTIVE = 'active',
  ACTIVE_EXITING = 'active_exiting',
  ACTIVE_SLASHED = 'active_slashed',
  EXITED_UNSLASHED = 'exited_unslashed',
  EXITED_SLASHED = 'exited_slashed',
  WITHDRAWAL_POSSIBLE = 'withdrawal_possible',
  WITHDRAWAL_DONE = 'withdrawal_done',
  WITHDRAWAL = 'withdrawal',
  EXITED = 'exited',
  NON_REGISTERED = 'non_registered',
  REGISTERED = 'registered',
}
