apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leequid-protocol-monitoring-{{ .Values.deployEnv }}
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      app: leequid-monitoring-service-{{ .Values.deployEnv }}
  endpoints:
    - port: http
      path: /metrics
      interval: 2m
